language: php
php:
  - 7.0
  - 7.1
before_install:
  - nvm install stable
  - npm update -g npm
install:
  # Composer
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer install
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
  # Newman
  - npm install -g newman
before_script:
  # Migrations
  - php vendor/bin/bluzman db:migrate
  - php vendor/bin/bluzman db:seed:run
  # Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
script:
  - mkdir .reports
  # Code style
  - php vendor/bin/phpcs ./application --standard=PSR1,PSR2 --encoding=utf-8 --ignore=./application/_loader.php
  # WebServer run
  - nohup bash -c "php -S 127.0.0.1:8000 -t ./public/ ./public/routing.php 2>&1 &" && sleep 1; cat nohup.out
  # CodeCeption
  - php vendor/bin/codecept run --coverage --coverage-xml -v
  # Newman run
  - newman run tests/postman/collection.json -e tests/postman/environment.json
after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b84e6a583d6eea87d0eb
      - https://webhooks.gitter.im/e/c4fa557829c5bd992271
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
